language: ruby
services:
  - mysql
  - redis-server
script:
  - RAILS_ENV=test bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database switchboard_test;'
